### ISSUE TITLE
راهنمایی

### ISSUE THREAD

**Issue by Bardiaengine** [glad-tidings/CoubBot#1]
سلام برای وارد کردنشان راهنمایی میخوام آیا ویدئو راهنما در یوتیوب دارید؟(ایردراپ)

**Comment by glad-tidings** [comment]
سلام در فایل data.txt در هر خط یک query_id را وارد کنید
از اسکریپت زیر برای دریافت query_id همه اکانتها می توانید استفاده کنید
https://github.com/glad-tidings/TelegramMiniAppQueryID

**Comment by Bardiaengine** [comment]
میشه توضیح کاملتر بدین؟
